### Start the scraping process
POST localhost:8000/scraper/start/

### Scraping status
GET localhost:8000/scraper/status/

### Stop the scraping process
POST localhost:8000/scraper/stop/

### force stop the scraping process
POST localhost:8000/scraper/force_stop/

### Reset scrapping process
POST localhost:8000/scraper/reset/
