### GET dummy Search API
GET http://localhost:8000/api/product/?min_price=1.00&max_price=2.00&limit=2&offset=0

### GET dummy Search Store ID
GET http://localhost:8000/api/product/?limit=20&offset=0


### GET dummy product
GET http://localhost:8000/api/product/2000614400003

### GET dummy category
GET http://localhost:8000/api/categories/