### Start the scraping process
POST localhost:8000/api/scraper/start/
Content-Type: application/json
X-CSRFToken: dKY6O5Nb7lsCPBb48idofKHyxJbzgX16

{
  "target_slug": "all"
}


### Scraping status
GET localhost:8000/api/scraper/status/

### Stop the scraping process
POST localhost:8000/api/scraper/stop/
X-CSRFToken: dKY6O5Nb7lsCPBb48idofKHyxJbzgX16

### force stop the scraping process
POST localhost:8000/api/scraper/force_stop/

### Reset scrapping process
POST localhost:8000/api/scraper/reset/
X-CSRFToken: dKY6O5Nb7lsCPBb48idofKHyxJbzgX16
