### signup

POST http://localhost:8000/api/user/signup/
Content-Type: application/json
X-CSRFToken: dKY6O5Nb7lsCPBb48idofKHyxJbzgX16

{
  "username": "test21",
  "email": "test1@test.tt",
  "password": "test"
}


###login
POST http://localhost:8000/api/user/login/
Content-Type: application/json
X-CSRFToken: qUHhex47wuEKsKfgwOsetOQu6fGDXLKB

{
  "username": "liqing",
  "password": "liqingliqing"
}
### logout
DELETE http://localhost:8000/api/user/login/
X-CSRFToken: qUHhex47wuEKsKfgwOsetOQu6fGDXLKB


### status
GET http://localhost:8000/api/user/profile/



### update user
PUT http://localhost:8000/api/user/account/
Content-Type: application/json
X-CSRFToken: oJHHV4d5mVPY996tpITHQvY62jaN0T8Y

{
  "oldPassword": "liqing",
  "newPassword": "liqingliqing"
}
